function conocer() {
  return {
    users: [
      {
        img: "https://i.pravatar.cc/400?img=61",
        nombre: "Aaren",
        edad: 20,
        ciudad: "Madrid",
        pais: "España",
        km: 20,
        offline: true,
        favorito: false,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=42",
        nombre: "Adi",
        edad: 19,
        ciudad: "Barcelona",
        pais: "España",
        km: 10,
        offline: false,
        favorito: true,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=56",
        nombre: "Grier",
        edad: 25,
        ciudad: "Madrid",
        pais: "España",
        km: 20,
        offline: true,
        favorito: false,
        nuevo: true,
        mensaje: false,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=36",
        nombre: "Harlie",
        edad: 22,
        ciudad: "Torreon",
        pais: "México",
        km: 400,
        offline: false,
        favorito: false,
        nuevo: false,
        mensaje: true,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=16",
        nombre: "Linell",
        edad: 30,
        ciudad: "Querétaro",
        pais: "México",
        km: 410,
        offline: false,
        favorito: false,
        nuevo: false,
        mensaje: false,
        noImagen: true,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=21",
        nombre: "Ingrid",
        edad: 27,
        ciudad: "San Cabos",
        pais: "Guatemala",
        km: 280,
        offline: true,
        favorito: false,
        nuevo: true,
        mensaje: false,
        noImagen: true,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=5",
        nombre: "Zulema",
        edad: 24,
        ciudad: "Marquesino",
        pais: "Colombia",
        km: 100,
        offline: false,
        favorito: true,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=3",
        nombre: "Wynn",
        edad: 35,
        ciudad: "Madrid",
        pais: "España",
        km: 10,
        offline: false,
        favorito: false,
        nuevo: true,
        mensaje: true,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=1",
        nombre: "Vittoria",
        edad: 60,
        ciudad: "Los Cabos",
        pais: "México",
        km: 580,
        offline: false,
        favorito: true,
        nuevo: false,
        mensaje: true,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=33",
        nombre: "Trudey",
        edad: 22,
        ciudad: "Capula",
        pais: "Argentina",
        km: 390,
        offline: false,
        favorito: false,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=10",
        nombre: "Tuesday",
        edad: 28,
        ciudad: "California",
        pais: "EUA",
        km: 200,
        offline: false,
        favorito: true,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=41",
        nombre: "Tillie",
        edad: 23,
        ciudad: "Madrid",
        pais: "España",
        km: 18,
        offline: false,
        favorito: false,
        nuevo: false,
        mensaje: false,
        noImagen: true,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=68",
        nombre: "Tamiko",
        edad: 27,
        ciudad: "Venecia",
        pais: "Italia",
        km: 63,
        offline: false,
        favorito: true,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=43",
        nombre: "Lindi",
        edad: 28,
        ciudad: "Toronto",
        pais: "Canada",
        km: 28,
        offline: true,
        favorito: false,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: true,
      },
      {
        img: "https://i.pravatar.cc/400?img=45",
        nombre: "Suzanna",
        edad: 35,
        ciudad: "Las Calles",
        pais: "Brasil",
        km: 490,
        offline: true,
        favorito: false,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: true,
      },
    ],

    likes: [
      {
        img: "https://i.pravatar.cc/400?img=61",
        nombre: "Aaren",
        edad: 20,
        ciudad: "Madrid",
        pais: "España",
        km: 20,
        offline: true,
        favorito: false,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: true,
      },
      {
        img: "https://i.pravatar.cc/400?img=42",
        nombre: "Adi",
        edad: 19,
        ciudad: "Barcelona",
        pais: "España",
        km: 10,
        offline: false,
        favorito: true,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: true,
      },
      {
        img: "https://i.pravatar.cc/400?img=56",
        nombre: "Grier",
        edad: 25,
        ciudad: "Madrid",
        pais: "España",
        km: 20,
        offline: true,
        favorito: false,
        nuevo: true,
        mensaje: false,
        noImagen: false,
        bloqueado: true,
      },
      {
        img: "https://i.pravatar.cc/400?img=36",
        nombre: "Harlie",
        edad: 22,
        ciudad: "Torreon",
        pais: "México",
        km: 400,
        offline: false,
        favorito: false,
        nuevo: false,
        mensaje: true,
        noImagen: false,
        bloqueado: true,
      },
      {
        img: "https://i.pravatar.cc/400?img=16",
        nombre: "Linell",
        edad: 30,
        ciudad: "Querétaro",
        pais: "México",
        km: 410,
        offline: false,
        favorito: false,
        nuevo: false,
        mensaje: false,
        noImagen: true,
        bloqueado: true,
      },
      {
        img: "https://i.pravatar.cc/400?img=21",
        nombre: "Ingrid",
        edad: 27,
        ciudad: "San Cabos",
        pais: "Guatemala",
        km: 280,
        offline: true,
        favorito: false,
        nuevo: true,
        mensaje: false,
        noImagen: true,
        bloqueado: true,
      },
      {
        img: "https://i.pravatar.cc/400?img=5",
        nombre: "Zulema",
        edad: 24,
        ciudad: "Marquesino",
        pais: "Colombia",
        km: 100,
        offline: false,
        favorito: true,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: true,
      },
      {
        img: "https://i.pravatar.cc/400?img=3",
        nombre: "Wynn",
        edad: 35,
        ciudad: "Madrid",
        pais: "España",
        km: 10,
        offline: false,
        favorito: false,
        nuevo: true,
        mensaje: true,
        noImagen: false,
        bloqueado: true,
      },
      {
        img: "https://i.pravatar.cc/400?img=1",
        nombre: "Vittoria",
        edad: 60,
        ciudad: "Los Cabos",
        pais: "México",
        km: 580,
        offline: false,
        favorito: true,
        nuevo: false,
        mensaje: true,
        noImagen: false,
        bloqueado: true,
      },
      {
        img: "https://i.pravatar.cc/400?img=33",
        nombre: "Trudey",
        edad: 22,
        ciudad: "Capula",
        pais: "Argentina",
        km: 390,
        offline: false,
        favorito: false,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: true,
      },
      {
        img: "https://i.pravatar.cc/400?img=10",
        nombre: "Tuesday",
        edad: 28,
        ciudad: "California",
        pais: "EUA",
        km: 200,
        offline: false,
        favorito: true,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: true,
      },
      {
        img: "https://i.pravatar.cc/400?img=41",
        nombre: "Tillie",
        edad: 23,
        ciudad: "Madrid",
        pais: "España",
        km: 18,
        offline: false,
        favorito: false,
        nuevo: false,
        mensaje: false,
        noImagen: true,
        bloqueado: true,
      },
      {
        img: "https://i.pravatar.cc/400?img=68",
        nombre: "Tamiko",
        edad: 27,
        ciudad: "Venecia",
        pais: "Italia",
        km: 63,
        offline: false,
        favorito: true,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: true,
      },
      {
        img: "https://i.pravatar.cc/400?img=43",
        nombre: "Lindi",
        edad: 28,
        ciudad: "Toronto",
        pais: "Canada",
        km: 28,
        offline: true,
        favorito: false,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: true,
      },
      {
        img: "https://i.pravatar.cc/400?img=45",
        nombre: "Suzanna",
        edad: 35,
        ciudad: "Las Calles",
        pais: "Brasil",
        km: 490,
        offline: true,
        favorito: false,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: true,
      },
    ],

    favoritos: [
      {
        img: "https://i.pravatar.cc/400?img=61",
        nombre: "Aaren",
        edad: 20,
        ciudad: "Madrid",
        pais: "España",
        km: 20,
        offline: true,
        favorito: true,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=42",
        nombre: "Adi",
        edad: 19,
        ciudad: "Barcelona",
        pais: "España",
        km: 10,
        offline: false,
        favorito: true,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=56",
        nombre: "Grier",
        edad: 25,
        ciudad: "Madrid",
        pais: "España",
        km: 20,
        offline: true,
        favorito: true,
        nuevo: true,
        mensaje: false,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=36",
        nombre: "Harlie",
        edad: 22,
        ciudad: "Torreon",
        pais: "México",
        km: 400,
        offline: false,
        favorito: true,
        nuevo: false,
        mensaje: true,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=16",
        nombre: "Linell",
        edad: 30,
        ciudad: "Querétaro",
        pais: "México",
        km: 410,
        offline: false,
        favorito: true,
        nuevo: false,
        mensaje: false,
        noImagen: true,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=21",
        nombre: "Ingrid",
        edad: 27,
        ciudad: "San Cabos",
        pais: "Guatemala",
        km: 280,
        offline: true,
        favorito: true,
        nuevo: true,
        mensaje: false,
        noImagen: true,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=5",
        nombre: "Zulema",
        edad: 24,
        ciudad: "Marquesino",
        pais: "Colombia",
        km: 100,
        offline: false,
        favorito: true,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=3",
        nombre: "Wynn",
        edad: 35,
        ciudad: "Madrid",
        pais: "España",
        km: 10,
        offline: false,
        favorito: true,
        nuevo: true,
        mensaje: true,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=1",
        nombre: "Vittoria",
        edad: 60,
        ciudad: "Los Cabos",
        pais: "México",
        km: 580,
        offline: false,
        favorito: true,
        nuevo: false,
        mensaje: true,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=33",
        nombre: "Trudey",
        edad: 22,
        ciudad: "Capula",
        pais: "Argentina",
        km: 390,
        offline: false,
        favorito: true,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=10",
        nombre: "Tuesday",
        edad: 28,
        ciudad: "California",
        pais: "EUA",
        km: 200,
        offline: false,
        favorito: true,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=41",
        nombre: "Tillie",
        edad: 23,
        ciudad: "Madrid",
        pais: "España",
        km: 18,
        offline: false,
        favorito: true,
        nuevo: false,
        mensaje: false,
        noImagen: true,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=68",
        nombre: "Tamiko",
        edad: 27,
        ciudad: "Venecia",
        pais: "Italia",
        km: 63,
        offline: false,
        favorito: true,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=43",
        nombre: "Lindi",
        edad: 28,
        ciudad: "Toronto",
        pais: "Canada",
        km: 28,
        offline: true,
        favorito: true,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: false,
      },
      {
        img: "https://i.pravatar.cc/400?img=45",
        nombre: "Suzanna",
        edad: 35,
        ciudad: "Las Calles",
        pais: "Brasil",
        km: 490,
        offline: true,
        favorito: true,
        nuevo: false,
        mensaje: false,
        noImagen: false,
        bloqueado: false,
      },
    ],
  };
}